apiVersion: v1
kind: Service
metadata:
  name: inspector
  namespace: istio-system
  labels:
    app: inspector
    yanxuan/app: inspector
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: http
      protocol: manager
      port: 8090
      targetPort: 8090
  selector:
    app: inspector
    yanxuan/app: inspector
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: inspector
    yanxuan/app: inspector
  name: inspector
  namespace: istio-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inspector
      yanxuan/app: inspector
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        sidecar.istio.io/inject: "false"
      labels:
        app: inspector
        yanxuan/app: inspector
    spec:
      containers:
        - args:
            - --currentCluster={{dev | test | online}}
            - --crdCrontabCycle=0 1 * * *
            - --redisCrontabCycle=*/30 * * * *
            - --defaultStrategyTime=2592000000
          image: {{hub.c.163.com/qingzhou/istio/inspector:202006241555}}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 15
          name: app
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 4Gi
            requests:
              cpu: "4"
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qingzhou-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: inspector-service-account
      serviceAccountName: inspector-service-account
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: inspector
  name: inspector-service-account
  namespace: istio-system
secrets:
  - name: inspector-service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inspector
subjects:
  - kind: ServiceAccount
    name: inspector-service-account
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io